{% set version = "0.03c" %}
{% set name = "PyOrgMode" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 798c89a4d84b0127c26e04377776a0a5f001194976edca93127aa5edddb01ffb

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/bjonnh/PyOrgMode
  license: GPLv3
  # https://github.com/bjonnh/PyOrgMode/pull/29
  # license_file: LICENSE
  summary: A python class for reading and writing orgmode files

extra:
  recipe-maintainers:
    - jschueller
