travis:
  secure:
    BINSTAR_TOKEN: baSIqBszY9mLuq7mY7cB+UVIzigBVWzkfD6QTBzA/cRNSF5FxjIB4HZ/AWExeXTAzNpQ4ZwnMHiCBEMD7eInLIynfLNynFmL4SLX6iGHyi0Y2BdMRs0pxyXp9OIwwE91IcG0KHpr1FFscW3LZtnbsYYzp/F0Z3bQYPVMoVFTgPzJWrDzCw78LVrZN26p09qDUxbQAoA6uqYxhJHVE4dol9Pzx257dr/lrDmLSbkgcAGFMAY92oduXhkx+EFnIgiIlP9x8z4dAK+Si/zSgyFrCg8H5BuGsVpsD+mtncU57dgSTc6NxRiSqHOKP2ZxBWcOUwh5sNIoAQKM9V6C0h11gAXCYsPb7HlzjC9NtyT8I6HsXm6XzDQo2TRHExTbpuGGmFDrMsCIY0IuvucVxIh4DEQJKmdUqwnI7j30+Hz9H+XlHz+go9FRhuw80Bv3CioIcwWWV/SVvIvQjhxbrRc6DtJo2qKBNGLm8LNP14qSwRm/MnDOFlq/Xzc77F0z2BBmwNSPn9+hFzVplIIRSZit9tjosULtsklRKUIXRoyth6Kxmf3lcUczTMRilLSNXO0Cq3xrK+z07/JzBxTOEZQz7/jFyoLX8189OkpHLnavts5FP48GX22XSUxcQrV8XxY1I8Ps26oH1KcBfU05UZaXcRBYlrycxqeyW0FgCXv3hck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
