travis:
  secure:
    BINSTAR_TOKEN: Ng9a69MbV5wbm+mZDLHNqrs6o8euJceF3cx2NQrL4NrJf9X0/it9hOSMlYhPYL3mxexZ8jn9qPl2AAiA648RKKOH+yw4hbWVgcxEuGHHhbECp1Cev+9T00ZsuT2jMo39xGFiGVTYqsgfu3807UudCzGIcmKG01ElL51OJcBHdqbJ4YaLplNTSM8lWjFZrWJiJREjINibdQsy2C9rLZBRgF+nPFTs47/bXjegwXf0DaMDiP0EyMycvtLa32XUasfTZasXQow9VTMO9ZI9SNwF+BeVqwGYoJazL8ST2SUgsbZc7KI9/6yipRm6OwI8oLdtld0KYXtTSuragOaOeRKGs6uNWVT2bZsTRWplu6mx9zUKqfSbf0IndR4A854AZ9qsfuNji0aXmbUHY5Pzj5M0icJXvPLxN20LqicnwQb5ySh/KE6ydY1oCT9pXiRjCqrxXxk9+SdVhHd70VaV+ac5CXWjIGVibbugLDPMRaTRvU8P8kPuGlMT532hADeBBOATBFGBs+KjhbLDeZncnS7oQwPFgvy4v1BMvmeWNNPYJUTDx/0yuFXMCV1DU5T6XbuQjN0aQFwBRLdZ+2RC+PH2KTZXhKZpmU1COla0ZdGN2eivjasvMR6HfrYGHbXaeGL5nluW5EK+mIzZD1NTm1CGpOgn9Uc49P2R2jkkfPzb1pU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
